/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStudyRouteImport } from './routes/app.study'
import { Route as AppSkillsRouteImport } from './routes/app.skills'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRoadmapRouteImport } from './routes/app.roadmap'
import { Route as AppResourcesRouteImport } from './routes/app.resources'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMentorRouteImport } from './routes/app.mentor'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppCertificatesRouteImport } from './routes/app.certificates'
import { Route as AppCareerRouteImport } from './routes/app.career'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudyRoute = AppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorRoute = AppMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerRoute = AppCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/career': typeof AppCareerRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/study': typeof AppStudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/career': typeof AppCareerRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/study': typeof AppStudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/career': typeof AppCareerRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/study': typeof AppStudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/career'
    | '/app/certificates'
    | '/app/community'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/mentor'
    | '/app/profile'
    | '/app/projects'
    | '/app/resources'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/skills'
    | '/app/study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/career'
    | '/app/certificates'
    | '/app/community'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/mentor'
    | '/app/profile'
    | '/app/projects'
    | '/app/resources'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/skills'
    | '/app/study'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/career'
    | '/app/certificates'
    | '/app/community'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/mentor'
    | '/app/profile'
    | '/app/projects'
    | '/app/resources'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/skills'
    | '/app/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/study': {
      id: '/app/study'
      path: '/study'
      fullPath: '/app/study'
      preLoaderRoute: typeof AppStudyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skills': {
      id: '/app/skills'
      path: '/skills'
      fullPath: '/app/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roadmap': {
      id: '/app/roadmap'
      path: '/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentor': {
      id: '/app/mentor'
      path: '/mentor'
      fullPath: '/app/mentor'
      preLoaderRoute: typeof AppMentorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates': {
      id: '/app/certificates'
      path: '/certificates'
      fullPath: '/app/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career': {
      id: '/app/career'
      path: '/career'
      fullPath: '/app/career'
      preLoaderRoute: typeof AppCareerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCareerRoute: typeof AppCareerRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppMentorRoute: typeof AppMentorRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppStudyRoute: typeof AppStudyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCareerRoute: AppCareerRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppMentorRoute: AppMentorRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppStudyRoute: AppStudyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
